language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

# Travis gives UnicodeDecodeError in pypy3, as if LANG were unset
#    - "pypy3"

install:
    - "if [[ $TRAVIS_PYTHON_VERSION = '3.2' ]]; then pip3 install enum34; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION = '3.3' ]]; then pip3 install enum34; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION = 'pypy3' ]]; then pip3 install enum34; fi"

script:
    - ./t/run-tests


notifications:
    irc:
        channels:
            - secure: "PB6mw8GV3wIZ75WCNjVwBIzXFjSkJWzWSCxNMggJutsNBbDGJfm0KuWDNgYUtyYYwXIaQOHo7wMKfQsUjzDbnzxbJxxH9Vt8fXhT4qW2Bx0dug7YduUHHJCFHuA+5B1o7ak7+WWnwkidQv9XOQr7MD7QAG60DMmLWU3qiPKGyqg="
    on_failure: always
        on_success: never
# The irc channel is encrypted for goavki/streamparser, so build notifications from forks won't show up on the IRC channel
# Encrypt with:
# $ gem install --user-install travis
# $ ~/.gem/ruby/*/bin/travis encrypt -r goavki/streamparser 'chat.freenode.net#apertium'

