language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
#    - "pypy3"

install:
    - pip3 install flake8 coveralls mypy

script:
    - flake8 *.py
    - coverage run -m unittest test
    - mypy streamparser.py --strict

after_success:
    - coveralls

notifications:
    irc:
        channels:
            - secure: "PB6mw8GV3wIZ75WCNjVwBIzXFjSkJWzWSCxNMggJutsNBbDGJfm0KuWDNgYUtyYYwXIaQOHo7wMKfQsUjzDbnzxbJxxH9Vt8fXhT4qW2Bx0dug7YduUHHJCFHuA+5B1o7ak7+WWnwkidQv9XOQr7MD7QAG60DMmLWU3qiPKGyqg="
    on_failure: always
    on_success: never

# The irc channel is encrypted for apertium/streamparser, so build notifications from forks won't show up on the IRC channel
# Encrypt with:
# $ gem install --user-install travis
# $ ~/.gem/ruby/*/bin/travis encrypt -r apertium/streamparser 'chat.freenode.net#apertium'
