language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

# Travis gives UnicodeDecodeError in pypy3, as if LANG were unset
#    - "pypy3"

install:
    - "if [[ $TRAVIS_PYTHON_VERSION = '3.2' ]]; then pip3 install enum34; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION = '3.3' ]]; then pip3 install enum34; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION = 'pypy3' ]]; then pip3 install enum34; fi"

script:
    - ./t/run-tests

